(define (sum_of_squares_of_large_two x y z)
	(cond ((and (> x y) (> x z))
           (+ (* x x) 
              (if (> y z) 
                  (* y y)
                  (* z z)
              )
           )
          )
          ((and (> y x) (> y z))
           (+ (* y y) 
              (if (> x z) 
                  (* x x)
                  (* z z)
              )   
           )
          )
          ((and (> z x) (> z y))
           (+ (* z z) 
              (if (> x y) 
                  (* x x)
                  (* y y)
              )
           )
          )
    )  
)

(sum_of_squares_of_large_two 1 3 4)
